service: news-reader
org: news-reader

provider:
  name: aws
  runtime: python3.6

functions:
  alpaca-sell:
    # Always <filename>.<function-to-execute>
    handler: handler.hello

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    usePipenv: true
    # True if using numpy, pandas, or other package with C dependencies. Requires Docker installation
    dockerizePip: true