org: ankitdeogharia
service: ankit-example

provider:
  name: aws
  runtime: python3.7

functions:
  ankit-example:
    # Always <filename>.<function-to-execute>
    handler: handler.hello

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    usePipenv: false
    # True if using numpy, pandas, or other package with C dependencies. Requires Docker installation
    dockerizePip: false
